routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect(route('backoffice.desktop.index'));
// })->middleware('auth');

Route::get('/', 'LandingController@index');
Route::post('/backoffice/getCriteria', 'Backoffice\IndexController@getCriteria');


Route::as('backoffice.')
    ->prefix('/backoffice')
    ->middleware(['auth'])
    ->namespace('Backoffice')
    ->group(function () {

        Route::post('/export', 'IndexController@export')->name('export');

        Route::get('/noaccess', function () {
            return view('backoffice.noaccess');
        })->name('noaccess');

        Route::get('/', 'IndexController@index')->name('index');
        Route::get('/download', 'IndexController@download')->name('download');

        //Рабочий стол
        Route::as('desktop.')
            ->prefix('/desktop')
            ->namespace('Desktop')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                // Route::get('/parcer', 'IndexController@parcer')->name('parcer');
                // Route::post('/parcer', 'IndexController@parcer')->name('parcer');
                // Route::post('/expert', 'IndexController@expert')->name('expert');
                // Route::get('/expert/{id}', 'IndexController@view')->name('expert.view');
                // Route::get('/download-file', 'IndexController@downloadFile')->name('download-file');
            });

        //Экспертиза
        Route::as('expertise.')
            ->prefix('/expertise')
            ->namespace('Expertise')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/parcer', 'IndexController@parcer')->name('parcer');
                Route::post('/parcer', 'IndexController@parcer')->name('parcer');
                Route::post('/expert', 'IndexController@expert')->name('expert');
                Route::get('/expert/{id}', 'IndexController@view')->name('expert.view');
                Route::get('/download-file', 'IndexController@downloadFile')->name('download-file');
            });

        //Для эксперта
        Route::as('expert.')
            ->prefix('/expert')
            ->namespace('Expert')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
            });

        //Журнал
        Route::as('journal.')
            ->prefix('/journal')
            ->namespace('Journal')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
            });

        //Аналитика
        Route::as('analytics.')
            ->prefix('/analytics')
            ->namespace('Analytics')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
            });

        //Диагнозы
        Route::as('diagnoses.')
            ->prefix('/diagnoses')
            ->namespace('Diagnoses')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/{id}', 'IndexController@edit')->name('edit');
                Route::post('/store', 'IndexController@store')->name('store');
                Route::post('/update', 'IndexController@update')->name('update');
                Route::post('/delete', 'IndexController@delete')->name('delete');

                Route::get('/{id}/criterias', 'IndexController@criterias')->name('criterias');
                Route::get('/{id}/examinations', 'IndexController@examinations')->name('examinations');
                Route::get('/{id}/treatments', 'IndexController@treatments')->name('treatments');

                Route::get('/similar/{id}', 'IndexController@similar')->name('similar');
                
                
            });

        // Обследования/Лечение
        Route::as('examinations.')
            ->prefix('/examinations')
            ->namespace('Examinations')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/{id}', 'IndexController@edit')->name('edit');
                Route::post('/store', 'IndexController@store')->name('store');
                Route::post('/update', 'IndexController@update')->name('update');
                Route::post('/delete', 'IndexController@delete')->name('delete');     
            });


        //Документация API
        Route::as('docs.')
            ->prefix('/docs')
            ->namespace('Docs')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
            });

        //Аналитика
        Route::as('similar.')
            ->prefix('/similar')
            ->namespace('Similar')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::post('/getExaminations', 'IndexController@getExaminations');
                Route::post('/saveExam', 'IndexController@saveExam');
            });

        // Управление пользователями
        Route::as('users.')
            ->prefix('/users')
            ->namespace('Users')
            ->middleware(['isSuperadmin'])
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/add', 'IndexController@add')->name('add');
                Route::get('/edit/{id}', 'IndexController@edit')->name('edit');
                Route::get('/edit/{user_id}/application/{application_id}', 'IndexController@application')->name('application');
                Route::post('/store', 'IndexController@store')->name('store');
                Route::post('/update', 'IndexController@update')->name('update');
                Route::post('/delete', 'IndexController@delete')->name('delete');
            });

        // Раздел компании
        Route::as('company.')
            ->prefix('/company')
            ->namespace('Company')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/edit', 'IndexController@edit')->name('edit');
                Route::post('/store', 'IndexController@store')->name('store');
                Route::post('/update', 'IndexController@update')->name('update');
                Route::post('/delete', 'IndexController@delete')->name('delete');
                Route::post('/data', 'IndexController@getDataByInn')->name('data');
                Route::post('/searchDataByInn', 'IndexController@searchDataByInn')->name('searchDataByInn');
            });

        // Раздел мои заявки
        Route::as('application.')
            ->prefix('/application')
            ->namespace('Application')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/add', 'IndexController@add')->name('add');
                Route::get('/edit/{id}', 'IndexController@edit')->name('edit');
                Route::post('/store', 'IndexController@store')->name('store');
                Route::post('/update', 'IndexController@update')->name('update');
                Route::post('/delete', 'IndexController@delete')->name('delete');
                Route::post('/status', 'IndexController@status')->name('status');
            });

        // Раздел все заявки
        Route::as('applications.')
            ->prefix('/applications')
            ->namespace('Applications')
            ->middleware(['isSuperadmin'])
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
                Route::get('/application/{id}', 'IndexController@application')->name('application');
            });

        //Раздел конкурсы
        Route::as('tender.')
            ->prefix('/tender')
            ->namespace('Tender')
            ->group(function () {
                Route::get('/', 'IndexController@index')->name('index');
            });
    });

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Backoffice/Analytics/IndexController.php
<?php

namespace App\Http\Controllers\Backoffice\Analytics;

use App\Http\Controllers\Controller;
use App\Services\ExpertService;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    protected ExpertService $expertService;

    public function __construct(
        ExpertService $expertService
    ) {
        $this->expertService = $expertService;
    }

    public function index()
    {
        $expertService = $this->expertService->getAll();

        $count = [
            'all'          => $expertService->count(),
            'allError'     => 0,
            'criteria'     => 0,
            'examinations' => 0,
            'treatment'    => 0,
            'dynamic'      => [],
            'noyabr'       => 0,
            'urengoy'      => 0,
        ];

        foreach($expertService as $expert) {
            $count['criteria'] = $count['criteria'] + $expert->count_error_criteria;
            $count['examinations'] = $count['examinations'] + $expert->count_error_examination;
            $count['treatment'] = $count['treatment'] + $expert->count_error_treatment;
            array_push($count['dynamic'], $count['criteria'] + $count['examinations'] + $count['treatment']);
           

            // Новоуренгойская ЦГБ
            switch($expert->hospital) {
                case 'Ноябрьская ЦГБ':
                    $count['noyabr'] = $count['criteria'] + $count['examinations'] + $count['treatment'];
                    break;
                case 'Новоуренгойская ЦГБ':
                    $count['urengoy'] = $count['criteria'] + $count['examinations'] + $count['treatment'];
                break;
            }
        }

        $count['allError'] =  $count['allError'] + $count['criteria'] + $count['examinations'] + $count['treatment'];
        
        $count['noyabr']  = ($count['noyabr'] * 100 ) / ($count['noyabr'] + $count['urengoy']);
        $count['urengoy'] = ($count['urengoy'] * 100 ) / ($count['noyabr'] + $count['urengoy']);

        

        return view('backoffice.analytics.index', compact('expertService', 'count'));
    }
}

app/Http/Controllers/Backoffice/Desktop/IndexController.php
<?php

namespace App\Http\Controllers\Backoffice\Desktop;

use App\Http\Controllers\Backoffice\Desktop\Requests\IndexRequest;
use App\Http\Controllers\Controller;
use App\Models\Criteria;
use App\Models\Examination;
use App\Models\Expert;
use App\Services\CriteriaService;
use App\Services\DiagnosisService;
use App\Services\ExpertService;
use App\Services\ParcerService;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    /**
     * @var ExpertService
     */
    protected ExpertService $expertService;

    public function __construct(
        ExpertService $expertService
    ) {
        $this->expertService = $expertService;
    }

    public function index()
    {       
        $expertService = $this->expertService->getAll();

        $count = [
            'all'          => $expertService->count(),
            'allError'     => 0,
            'criteria'     => 0,
            'examinations' => 0,
            'treatment'    => 0,
            'dynamic'      => [],
            'noyabr'       => 0,
            'urengoy'      => 0,
        ];

        foreach($expertService as $expert) {
            $count['criteria'] = $count['criteria'] + $expert->count_error_criteria;
            $count['examinations'] = $count['examinations'] + $expert->count_error_examination;
            $count['treatment'] = $count['treatment'] + $expert->count_error_treatment;
            array_push($count['dynamic'], $count['criteria'] + $count['examinations'] + $count['treatment']);
           

            // Новоуренгойская ЦГБ
            switch($expert->hospital) {
                case 'Ноябрьская ЦГБ':
                    $count['noyabr'] = $count['criteria'] + $count['examinations'] + $count['treatment'];
                    break;
                case 'Новоуренгойская ЦГБ':
                    $count['urengoy'] = $count['criteria'] + $count['examinations'] + $count['treatment'];
                break;
            }
        }

        $count['allError'] =  $count['allError'] + $count['criteria'] + $count['examinations'] + $count['treatment'];
        
        $count['noyabr']  = ($count['noyabr'] * 100 ) / ($count['noyabr'] + $count['urengoy']);
        $count['urengoy'] = ($count['urengoy'] * 100 ) / ($count['noyabr'] + $count['urengoy']);

        return view('backoffice.desktop.index', compact('expertService', 'count'));
    }

}

app/Http/Controllers/Backoffice/Desktop/Requests/IndexRequest.php
<?php

namespace App\Http\Controllers\Backoffice\Desktop\Requests;

use Illuminate\Foundation\Http\FormRequest;

class IndexRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'htmlFile' => 'required|max:10000|mimes:html,htm',
        ];
    }



    public function messages()
    {
        return [
            'htmlFile.required' => 'Вы не выбрали файл',
        ];
    }
}

app/Http/Controllers/Backoffice/Diagnoses/IndexController.php
<?php

namespace App\Http\Controllers\Backoffice\Diagnoses;

use App\Http\Controllers\Backoffice\Diagnoses\Requests\DeleteRequest;
use App\Http\Controllers\Backoffice\Diagnoses\Requests\StoreRequest;
use App\Http\Controllers\Backoffice\Diagnoses\Requests\UpdateRequest;
use App\Http\Controllers\Backoffice\Users\Requests\UserUpdateRequest;
use App\Http\Controllers\Controller;
use App\Services\DiagnosisService;
use App\Services\ExaminationService;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    /**
     * @var DiagnosisService
     */
    protected DiagnosisService $diagnosisService;

    /**
     * @var ExaminationService
     */
    protected ExaminationService $examinationService;

    public function __construct(
        DiagnosisService   $diagnosisService,
        ExaminationService $examinationService
    )   {
        $this->diagnosisService   = $diagnosisService;
        $this->examinationService = $examinationService;
    }

    public function index()
    {
        $diagnoses = $this->diagnosisService->getAllPaginate(5);
        return view('backoffice.diagnoses.index', compact('diagnoses'));
    }

    public function criterias($id)
    {
        $diagnos      = $this->diagnosisService->getById($id);
        $examinations = $this->examinationService->getByDiagnosIdWithoutSimilar($id, 'examination');
        $treatments   = $this->examinationService->getByDiagnosIdWithoutSimilar($id, 'treatment');
        return view('backoffice.diagnoses.criterias', compact('diagnos', 'examinations', 'treatments'));
    }

    public function treatments($id)
    {
        $diagnos      = $this->diagnosisService->getById($id);
        $examinations   = $this->examinationService->getByDiagnosIdWithoutSimilar($id, 'treatment');
        return view('backoffice.diagnoses.examinations', compact('diagnos', 'examinations'));
    }

    public function examinations($id)
    {
        $diagnos      = $this->diagnosisService->getById($id);
        $examinations = $this->examinationService->getByDiagnosIdWithoutSimilar($id, 'examination');
        return view('backoffice.diagnoses.examinations', compact('diagnos', 'examinations'));
    }

    public function similar($id)
    {
        $exam    = $this->examinationService->getById($id);
        $similar = $this->examinationService->getSimilar($id);
        return view('backoffice.diagnoses.similar', compact('exam', 'similar'));
    }

    public function edit($id)
    {
        $diagnos = $this->diagnosisService->getById($id);
        return view('backoffice.diagnoses.edit', compact('diagnos'));
    }

    public function store(StoreRequest $request)
    {
        $diagnos = $this->diagnosisService->store($request->toArray());
        flash('Запись успешно добавлена!')->success();
        return back();
    }

    public function update(UpdateRequest $request)
    {
        $diagnos = $this->diagnosisService->update($request->toArray());
        flash('Запись успешно обновлена!')->success();
        return redirect(route('backoffice.diagnoses.index'));
    }

    public function delete(DeleteRequest $request)
    {
        $diagnos = $this->diagnosisService->delete($request->toArray());
        flash('Запись успешно удалена!')->success();
        return redirect(route('backoffice.diagnoses.index'));
    }
}

app/Http/Controllers/Backoffice/Docs/IndexController.php
<?php

namespace App\Http\Controllers\Backoffice\Docs;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index()
    {
        return view('backoffice.api.index');
    }
}

resources/views/backoffice/application/edit.blade.php
@extends('backoffice.layouts.vertical')


@section('css')

@endsection

@section('breadcrumb')
<div class="row page-title">
    <div class="col-md-12">
        <nav aria-label="breadcrumb" class="float-right mt-1">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Создание заявки</li>
            </ol>
        </nav>
        <h4 class="mb-1 mt-0">Создание заявки</h4>
    </div>
</div>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <p>
                    Заполните все обязательные поля и прикрепите файлы.
                </p>
                <form class="form-horizontal" method="POST" action="{{ route('backoffice.application.store') }}">
                    @csrf
                    <div class="row">
                        <div class="col-9">
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label">Выберете конкурс</label>
                                <div class="col-lg-10">
                                    <select class="form-control custom-select @error('indastry_id') is-invalid @enderror" name="indastry">
                                        @foreach($indastries as $indastry)
                                        <option value="{{ $indastry->id }}" {{ $indastry->id == old('indastry_id') ? 'selected' : '' }}>{{ $indastry->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('indastry_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label">Система налогооблажения</label>
                                <div class="col-lg-10">
                                    <select class="form-control custom-select @error('taxation_system_id') is-invalid @enderror" name="taxation_system_id">
                                        @foreach($taxationSystems as $taxationSystem)
                                        <option value="{{ $taxationSystem->id }}" {{ $taxationSystem->id == old('taxation_system_id') ? 'selected' : '' }}>{{ $taxationSystem->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('taxation_system_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="number_employees">Количество сотрудников</label>
                                <div class="col-lg-10">
                                    <input type="text" class="form-control @error('number_employees') is-invalid @enderror" id="number_employees" name="number_employees" value="{{ old('number_employees') }}">
                                    @error('number_employees')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="number_branches">Количество точек общественного питания</label>
                                <div class="col-lg-10">
                                    <input type="text" class="form-control @error('number_branches') is-invalid @enderror" id="number_branches" name="number_branches" value="{{ old('number_branches') }}">
                                    @error('number_branches')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label">Сколько работаете в сфере общественного питания</label>
                                <div class="col-lg-10">
                                    <select class="form-control custom-select @error('experience') is-invalid @enderror" name="experience">
                                        <option value="менее 1 года">Менее 1 года</option>
                                        <option value="от 1 до 3 лет">От 1 до 3 лет</option>
                                        <option value="более 3 лет">Более 3 лет</option>
                                    </select>
                                    @error('experience')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label">Ваши клиенты</label>
                                <div class="col-lg-10">
                                    <select class="form-control custom-select @error('client_id') is-invalid @enderror" name="client_id">
                                        @foreach($clients as $client)
                                        <option value="{{ $client->id }}" {{ $client->id == old('client_id') ? 'selected' : '' }}>{{ $client->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('client_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="companies">ИНН компаний с которыми работаете более 3 мес.</label>
                                <div class="col-lg-10">
                                    <input type="text" class="form-control @error('companies') is-invalid @enderror" id="companies" name="companies[]" value="{{ old('companies') }}">
                                    @error('companies')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="mt-5">
                                <h4 class="header-title">Прикрепите файлы</h4>
                                <p class="sub-header">
                                    Поддерживаемые форматы word, pdf
                                </p>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="commercial_proposal_file">Коммерческое предложение</label>
                                <div class="col-lg-10">
                                    <input type="file" class="form-control" name="commercial_proposal_file" id="commercial_proposal_file">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="menu_file">Меню с выходом блюд</label>
                                <div class="col-lg-10">
                                    <input type="file" class="form-control" name="menu_file" id="menu_file">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="assortiment_menu_file">Ассортимент меню</label>
                                <div class="col-lg-10">
                                    <input type="file" class="form-control" name="assortiment_menu_file" id="assortiment_menu_file">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-4 col-form-label" for="photo_set_lunch">Фото комплексного обеда (внешний вид, состав, упаковка)</label>
                                <div class="col-lg-10">
                                    <input type="file" class="form-control" name="photo_set_lunch" id="photo_set_lunch">
                                </div>
                            </div>
                            <div class="form-group mt-4">
                                <button type="submit" class="btn btn-outline-primary mb-3">Подать заявку</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div><!-- end col -->
</div>
<!-- end row -->
@endsection

@section('script')

@endsection

@section('script-bottom')
@endsection

resources/views/backoffice/application/index.blade.php
@extends('backoffice.layouts.vertical')


@section('css')

@endsection

@section('breadcrumb')
<div class="row page-title">
    <div class="col-md-12">
        <nav aria-label="breadcrumb" class="float-right mt-1">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Мои заявки</li>
            </ol>
        </nav>
        <h4 class="mb-1 mt-0">Мои заявки</h4>
    </div>
</div>
@endsection

@section('content')
@if (session('success'))
<div class="row">
    <div class="col">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    </div>
</div>
@endif
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <p>
                    На этой странице можно посмотреть информацию о своих заявках.
                </p>
                <a href="{{ route('backoffice.application.add') }}" class="btn btn-outline-primary mb-3">Добавить заявку</a>
                <table id="basic-datatable" class="table dt-responsive nowrap">
                    <thead>
                        <tr>
                            <th>Номер заявки</th>
                            <th>Описание события</th>
                            <th>Статус события</th>
                        </tr>
                    </thead>


                    <tbody>
                        @foreach($applications as $application)
                        <tr>
                            <td> <a href="{{ route('backoffice.application.edit', ['id' => $application->id]) }}">{{ $application->id }}</a> </td>
                            <td>{{ $application->indastry()->first()->name }}</td>
                            <td>  <span style="color: #c1c11f">{{ $application->status == 1 ? 'На рассмотрении' : ''  }}</span>
                            <span style="color: green">{{ $application->status == 2 ? 'Принята' : ''  }}</span>
                            <span style="color: gray"> {{ $application->status == 3 ? 'На доработке' : ''  }}</span>
                            <span style="color: red">   {{ $application->status == 4 ? 'Отклонена' : ''  }}</span>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div><!-- end col -->
</div>
<!-- end row -->
@endsection

@section('script')

@endsection

@section('script-bottom')
@endsection